# Generated by Django 4.1.5 on 2023-01-26 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('number_points', models.PositiveIntegerField(blank=True, default=0, verbose_name='Количество очков')),
            ],
            options={
                'verbose_name': 'Баланс',
                'verbose_name_plural': 'Баланс',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_birth', models.DateField(blank=True, null=True, verbose_name='Дата Рождения')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=profiles.models.get_name_photo_file, verbose_name='Фото')),
                ('quote', models.CharField(blank=True, max_length=100, null=True, verbose_name='Цитата')),
            ],
            options={
                'verbose_name': 'Информация о пользователе',
                'verbose_name_plural': 'Информация о пользователях',
            },
        ),
        migrations.CreateModel(
            name='Visual',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('base_background_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.basebackgroundcolor', verbose_name='Цвет основного фона')),
                ('text_background_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='text_background_color', to='shop.textbackgroundcolor', verbose_name='Цвет фона текста')),
                ('text_title_font', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.texttitlefont', verbose_name='Шрифт никнейма')),
            ],
            options={
                'verbose_name': 'Отображение карточки пользователя',
                'verbose_name_plural': 'Отображения карточек пользователя',
            },
        ),
    ]
