# Generated by Django 4.1.5 on 2023-01-11 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='point',
            options={'verbose_name': 'Баланс', 'verbose_name_plural': 'Баланс'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Информация о пользователе', 'verbose_name_plural': 'Информация о пользователях'},
        ),
    ]
