# Generated by Django 4.1.5 on 2023-01-20 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Заголовок')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('cost', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('slug', models.SlugField(max_length=1024, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='ElementQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024, unique=True, verbose_name='Текст')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='quizzes/elements/%Y/%m/%d', verbose_name='Фото')),
                ('category', models.CharField(choices=[('QUESTION', 'question'), ('ANSWER', 'answer')], default='Question', max_length=8, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Элемент вопроса',
                'verbose_name_plural': 'Элементы вопросов',
            },
        ),
        migrations.CreateModel(
            name='TextAnswer',
            fields=[
                ('basequestion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quizzes.basequestion')),
                ('correct_answer', models.CharField(max_length=512, verbose_name='Верный ответ')),
            ],
            options={
                'verbose_name': 'Текстовый вопрос',
                'verbose_name_plural': 'Текстовые вопросы',
            },
            bases=('quizzes.basequestion',),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Название')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='quizzes/tasks/%Y/%m/%d', verbose_name='Фото задания')),
                ('complexity', models.CharField(choices=[('EASY', 'easy'), ('MEDIUM', 'medium'), ('HARD', 'hard'), ('HARDCORE', 'hardcore')], default='easy', max_length=8, verbose_name='Сложность')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='URL')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('question', models.ManyToManyField(to='quizzes.basequestion', verbose_name='Вопросы задания')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.AddField(
            model_name='basequestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quizzes.elementquestion', verbose_name='Вопрос'),
        ),
        migrations.CreateModel(
            name='ChoiceAnswer',
            fields=[
                ('basequestion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quizzes.basequestion')),
                ('correct_answer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correct_answer', to='quizzes.elementquestion', verbose_name='Верный ответ')),
                ('wrong_answer_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wrong_answer_1', to='quizzes.elementquestion', verbose_name='Неверный ответ 1')),
                ('wrong_answer_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wrong_answer_2', to='quizzes.elementquestion', verbose_name='Неверный ответ 2')),
                ('wrong_answer_3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wrong_answer_3', to='quizzes.elementquestion', verbose_name='Неверный ответ 3')),
            ],
            options={
                'verbose_name': 'Выборочный вопрос',
                'verbose_name_plural': 'Выборочные вопросы',
            },
            bases=('quizzes.basequestion',),
        ),
    ]
